### ISSUE TITLE
EventSouce connection time out , in some case my app stop listening events in one mobile and it is listening to another mobile why??

### ISSUE THREAD

**Issue by rahulkumar7** [inaka/EventSource#102]

**Comment by rahulkumar7** [comment]
is There any Time out For Listening of Events?? Some times iam not getting data after some time?

**Comment by fatgue** [comment]
Do you find any solution?

**Comment by andresinaka** [comment]
If the connection drops the callback:
```
func onComplete(_ onComplete: @escaping ((Int?, Bool?, NSError?) -> Void))
```

Should be called. First parameter is the http status code returned by server, second parameter is if we should reconnect or not based on the w3c document and the third parameter is the session error if any.
With all this info you can take a decision on what todo and find out what's going on.
