### ISSUE TITLE
onOpen-onError is cyclically called

### ISSUE THREAD

**Issue by Kirill96** [inaka/EventSource#105]
What could be the cause of this problem? The EventSource reconnects, but an error always occurs and an onError is called, and the error = nil.

**Comment by andresinaka** [comment]
I pushes a big update that doesn't automatically reconnect. It lets you choose what to do after an error arises.

There is an `onComplete` callback that is called everytime the connection drops or server closes or there is an error. At that point is responsibility of the user to reconnect or how to act.

Take a look and let me know how it goes!
