### ISSUE TITLE
Importing problem in Swift

### ISSUE THREAD

**Issue by pavlem** [inaka/EventSource#106]
When I install via cocoa pods, as in your instruction, I cannot import the module, concretely, I get the message `No such module 'EventSource’`

Do you have any ideas?

**Comment by andresinaka** [comment]
Just to be sure @pavlem are you opening the workspace generated when `pod install`?

**Comment by pavlem** [comment]
Yes of course I am, I already have several pods and they are all working fine. For example, I am having the main project `ScanG.xcodeproj` and the workspace project `ScanG.xcworkspace` which I am using.

**Comment by pavlem** [comment]
I created a completely new project from scratch, so you can see the error. 
Link: https://github.com/pavlem/SSEventsTest

**Comment by pavlem** [comment]
As I see, you only have `EventSource.h` generated after pod install

**Comment by spiridonkopicl** [comment]
I have the same issue. Any help ? Thx

**Comment by nikolaschou** [comment]
Any news here? Any help will be greatly appreciated by me as well.

**Comment by andresinaka** [comment]
I'm taking a look right now, hopefully I can figure it out. In the meantime you can copy `EventSource/Sources/EventSource.swift` file into your project and that has to work.

**Comment by andresinaka** [comment]
@nikolaschou @spiridonkopicl @pavlem guys I just updated to Swift 5, merged some PRs and updated the pod. Everything should be working now. 

Update the pod:

```
pod update IKEventSource
```

I tested with @pavlem's test project and after updating the pod the project compiled perfectly. I'll try to make some space to keep maintaining this. I haven't worked on a long time on this and checked the code and there is a lot of space for improvement.

Please let me know if it's working for you guys too and I'll close the issue.

**Comment by pavlem** [comment]
@andresinaka thanks, the import now works, but it gives me weird feedback in Xcode.

```
2019-05-27 11:01:23.046348+0200 SGo[5597:253775] Task <28410D31-A8B9-44A7-A059-FD9BAE51C6DE>.<1> load failed with error Error Domain=NSURLErrorDomain Code=-999 "annulleret" UserInfo={NSErrorFailingURLStringKey=https://d-xxx.com/api/events?cs=userDevice, NSErrorFailingURLKey=https://d-xxx.com/api/events?cs=userDevice, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <28410D31-A8B9-44A7-A059-FD9BAE51C6DE>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <28410D31-A8B9-44A7-A059-FD9BAE51C6DE>.<1>, NSLocalizedDescription=annulleret} [-999]
2019-05-27 11:01:23.046523+0200 ScanAndGo[5597:253777] Task <28410D31-A8B9-44A7-A059-FD9BAE51C6DE>.<1> finished with error - code: -999
``` 

Just to note, I tried in the meantime with some other library and it works although that one has some buffer issues, but I can see the events coming (https://github.com/banjun/ReactiveSSE). Also, it is working on android totally fine via https://github.com/heremaps/oksse, so the server is not the issue.

**Comment by andresinaka** [comment]
mmm that's a weird error, it looks like the eventSource instance is getting dealloc... I just tried with the url in your example and it seems to connect but the server is not even returning a 200... weird

```
import UIKit
import IKEventSource

class ViewController: UIViewController {

    var eventSource: EventSource?

    override func viewDidLoad() {
        super.viewDidLoad()

        eventSource = EventSource(url: "https://d-xxx.com/api/events?cs=userDevice")

        eventSource?.onOpen {
            print("OPEN")
        }
    }
}
```

**Comment by pavlem** [comment]
Hello Adnre, 
I sent you the correct URL to your email.
