### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by onderweg** [inaka/EventSource#110]
Hi there,

Running `carthage update --platform macOS` results in:

```
Dependency "EventSource" has no shared framework schemes for any of the platforms: Mac
```

The readme does not mention that EventSource is a iOS only framework.
Will it run on Mac?

thanks in advance

**Comment by andresinaka** [comment]
It uses `NSURLSession` that is available on mac since `macOS 10.9+` so I think it should work. I'm not sure if it's going to work using cocoapods to install it but you can include the files on `EventSource` on your project and give it a try.
