### ISSUE TITLE
If App is Idle and still in same page with no new events from server, connection dropping and not listening further events. How can I overcome this issue?

### ISSUE THREAD

**Issue by ShivaSaiNethaRudra** [inaka/EventSource#111]

**Comment by andresinaka** [comment]
If the connection drops the callback:

```
func onComplete(_ onComplete: @escaping ((Int?, Bool?, NSError?) -> Void))
``` 

Should be called. First parameter is the http status code returned by server, second parameter is if we should reconnect or not based on the w3c document and the third parameter is the session error if any.
With all this info you can take a decision on what todo and find out what's going on.

**Comment by rahulkumar-ios** [comment]
> _No description provided._

@rssnetha  is the issue resolved? if not what have you done for this?

**Comment by rahulkumar-ios** [comment]
> _No description provided._
