### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by krjw** [inaka/EventSource#124]
I think it would be useful to add SPM support. I don't use any third party package managers and this library is great!

greetings, krjw

**Comment by Mohamed-Afsar** [comment]
@andresinaka Any plans to support this? Would be much helpful if its supported.

**Comment by andresinaka** [comment]
There is a PR pending I just need to make the time to review it and merge it.

**Comment by andresinaka** [comment]
Implemented on #134

**Comment by j-f1** [comment]
Can you tag a new release so we can add the package with just the GitHub URL instead of having to specify the commit?
