### ISSUE TITLE
no ios scheme on tags versions

### ISSUE THREAD

**Issue by MeGaPk** [inaka/EventSource#127]
Hi, carthage doesn't want to build ios, because  for ex in tag "3.0.1" doesn't exist ios scheme... In master it have. Please add this scheme to new version :)

**Comment by vincedev** [comment]
Also, taking latest [`master`](https://github.com/inaka/EventSource/commit/8d465e891b7c5d4d852ff39f7495fe9465a4275f#diff-6d71b2167f07dc8f748c67b3d64f52b8R354) sets minimum deployment target to iOS 13.

**Comment by vincedev** [comment]
This seems to have been fixed on latest master by 8d465e8
