### ISSUE TITLE
Not able to connect SSE Url with headers

### ISSUE THREAD

**Issue by sreejithjanardhanan** [inaka/EventSource#128]
I am getting following URL Error Domain=kCFErrorDomainCFNetwork Code=303 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x1c0289e70 [0x1b5a22310]>{length = 16, capacity = 16, bytes = 0x100201bb0fce90590000000000000000}, _kCFStreamErrorCodeKey=-2201, _kCFStreamErrorDomainKey=4}  When I try to hit URL with header ( User agent, Authorisation). It is not connecting only. After sometime disconnected call will happen. It will be really helpful if somebody guide me on this

**Comment by andresinaka** [comment]
If you try the endpoint with curl it works? @sreejithjanardhanan ?

**Comment by sreejithjanardhanan** [comment]
Hi @andresinaka  It got fixed. It was the end point problem. Thanks for the quick response.
