### ISSUE TITLE
How to set Time out  if no events or values coming from server

### ISSUE THREAD

**Issue by sreejithjanardhanan** [inaka/EventSource#136]
How to set time out  for socket connection if no events or values coming from server.

**Comment by andresinaka** [comment]
Hi @sreejithjanardhanan. The library doesn't take care of this scenario. One thing you can try is start a timer in the `func onOpen(_ onOpenCallback: @escaping (() -> Void))` delegate and every time you receive an event restart that timer... if for a long time you didn't receive anything the timer will call your delegate and that would be your time out.

Let me know how it went!

**Comment by sreejithjanardhanan** [comment]
Hi @andresinaka, Thanks will check with the timer and let you know.
