### ISSUE TITLE
Lost first message

### ISSUE THREAD

**Issue by sergeydi** [inaka/EventSource#162]
My Code:
```
let serverURL = URL(string: "my_url")!
eventSource = EventSource(url: serverURL, headers: ["Authorization": "my_token"])
eventSource?.connect()    
eventSource?.onOpen { [weak self] in
    print("CONNECTED")
}
eventSource?.onComplete { [weak self] statusCode, reconnect, error in
    print("DISCONNECTED")
}
eventSource?.onMessage { [weak self] id, event, data in
    print("Message received", data)
}
```
Xcode 13.4.1
IKEventSource 3.0.1

Each time I started my application and connected to the server, first new message don't arrive. From the next one everything works perfect. It is not on server side (at the same time to console curl client message arrive).
Any ideas why it happens?

**Comment by lpfrenette** [comment]
@sergeydi Were you able to fix this. I'm having the same issue.

**Comment by AdrienPiquoti** [comment]
@sergeydi @lpfrenette Were you able to fix this. I'm having the same issue. ??

**Comment by lpfrenette** [comment]
@AdrienPiquoti , As a workaround, in my backend i've created a /ping endpoint which then sends a PONG SSE. So that way i'm making sure that the first "real" SSE is processed as expected. Also i'm now sending the lastEventId when i have one.

Hope it helps

**Comment by AdrienPiquoti** [comment]
thx you :) it was my first solution too :D
