### ISSUE TITLE
Support HTTP 204 response for no content

### ISSUE THREAD

**Issue by danielsht86** [inaka/EventSource#23]
In cases where a server is sending a stream of content and wishes to end and close the connection, the current implementation will continue to reconnect.

Per the the spec at http://www.w3.org/TR/eventsource/:
`Clients will reconnect if the connection is closed; a client can be told to stop reconnecting using the HTTP 204 No Content response code.`

EventSource should support this feature and cease reconnecting if it tries to reconnect and receives a 204 response.

**Comment by andresinaka** [comment]
Done #33
