### ISSUE TITLE
Event source doesn't handle delimiters such as \r\n\r\n

### ISSUE THREAD

**Issue by GabrielHauber** [inaka/EventSource#57]
The extractEventsFromBuffer function hard-codes an expected delimiter of \n\n. However, delimiters can be e.g. \r\n\r\n, and the code won't recognise these.

See the spec here: https://html.spec.whatwg.org/multipage/comms.html#parsing-an-event-stream

specifically:

```
end-of-line   = ( cr lf / cr / lf )
lf            = %x000A ; U+000A LINE FEED (LF)
cr            = %x000D ; U+000D CARRIAGE RETURN (CR)
```

**Comment by liyong03** [comment]
@GabrielHauber , I think you need change the sse.js, which define the delimiter is "\n\n".
