### ISSUE TITLE
Remove the IK prefix from everywhere

### ISSUE THREAD

**Issue by volbap** [inaka/EventSource#64]
The IK prefix is still present in some places (the pod name, for example, is still `IKEventSource`). It should be removed from everywhere to keep consistency with the current name of the library, which is `EventSource`.

**Comment by andresinaka** [comment]
@volbap EventSource is already taken for CocoaPods name... if we can come up with a better name we can migrate it but I think we will be stuck with this :(

**Comment by volbap** [comment]
@andresinaka pity... I'm closing this issue. Let's keep thinking of a possible different name, though.
