### ISSUE TITLE
Swift 3 release

### ISSUE THREAD

**Issue by sashabelonogov** [inaka/EventSource#68]
Hello EventSource team, 

I noticed, that the PR with all the Swift 3 changes was merged, but there is still no tag for the most fresh version, so I would be able to use it via CocoaPods. Can it be created? If not, maybe you need some help there as my project depends on it.

**Comment by andresinaka** [comment]
hi @sashabelonogov! Sorry for the delay, we've been kind of busy. I just updated the pod, it's pointing to release  2.0.0 (swift 3.0 support) so everything should be ready to use!

Let me know if something goes wrong!
