### ISSUE TITLE
Custom NSURLSessionConfiguration

### ISSUE THREAD

**Issue by sascha-wolf** [inaka/EventSource#70]
ATM it's not possible to customise the `NSURLSessionConfiguration`. I thought about creating a pull request but I'm not sure what approach would make sense to allow the user to customise the configuration.

Our specific problem resolves around cookies; the service we use sets a session cookie which is undesirable as we want a "fresh" connection every time, since the service sends the initial system state at the beginning.

Any ideas on how this can be implemented?

**Comment by andresinaka** [comment]
hi @Zeeker! thanks for the interest in EventSource! Sorry for the delay, I've been super busy...

So you would need to set something like this to your NSURLSessionConfiguration???
```
configuration.HTTPCookieAcceptPolicy = .Never
```

maybe what we can do is have the EventSource init to receive an optional parameter configuration, save that config as an instance and use that as config when we create the session... if not we can just use that one that is currently using...

What do you think???

sorry again for the delay!

**Comment by sascha-wolf** [comment]
Hey @andresinaka, no problem, this issue is not pressing, as we came to an agreement with the people running the service. Nethertheless I think it might be useful in the future.

I considered the same approach; the issue is that EventSource sets some own configuration, so any user configuration in this fields would be overriden. If this is clearly communicated via debug logging and the documentation I see nothing which would stop us from doing it this way.

**Comment by andresinaka** [comment]
@Zeeker I agree this is going to be useful in the future! and about "the issue is that EventSource sets some own configuration, so any user configuration in this fields would be overriden." you are right! I think the best option is to create an other initializer that receives a config and uses that config and it's not overridden... I'll try to get this done!

Thanks for the feedback!

**Comment by andresinaka** [comment]
create an init that receives NSURLSessionConfiguration but be sure to always override 

```
configuration.timeoutIntervalForRequest = TimeInterval(INT_MAX)
configuration.timeoutIntervalForResource = TimeInterval(INT_MAX)
```
