### ISSUE TITLE
Cannot access stream data even though server connection established

### ISSUE THREAD

**Issue by Zerocool27** [inaka/EventSource#78]
I'm using nodejs with express on my server and authenticating users with token. Eventsource can establish connection to my server but I cannot access server event data even though I exactly copied the sse.js code just to test.  Here is authentication code;

let token = "Bearer tokenWithSecret"
self.eventSource = EventSource(url:server , headers: ["Authorization" : token])

self.eventSource?.onOpen {  
            print("onOpen")
}
onOpen callback works fine but others are not working. Funny side is nodejs client is working and getting server events properly.

**Comment by andresinaka** [comment]
it's really hard to debug this with no further info. You can try setting some breakpoints in

``` 
open func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive data: Data)
```

And see if that's called and follow the flor from there!
