### ISSUE TITLE
Ignored message if 'retry:' is included

### ISSUE THREAD

**Issue by biancalui** [inaka/EventSource#82]
When received messages that include 'retry:' value, the messages are ignored.
If 'retry:' is not in the last line, it cannot be parsed.

**Comment by andresinaka** [comment]
@biancalui can you give me an example of the Event you are receiving that is not changing the retry time?

**Comment by haaakon** [comment]
I also struggled with this, the error is at line 265, it ignores the message if it contains a retry. I made a fork and deleted the line, it then worked
<img width="577" alt="screen shot 2018-02-13 at 09 28 09" src="https://user-images.githubusercontent.com/1579465/36140101-54644a12-10a0-11e8-9bb9-b3ccf979c7b5.png">

**Comment by andresinaka** [comment]
@haaakon can you share with me how was the event structure that was failing??

**Comment by haaakon** [comment]
@andresinaka the json is proprietary, but basically was like this: 
event:eba349e32ca38
{ 
// json
}
retry:1000

**Comment by Rjayone** [comment]
Still actual

**Comment by andresinaka** [comment]
I made a huge refactor and update and this should be fixed. Please test and let me know!

**Comment by Rjayone** [comment]
Thank you, i will check!
