### ISSUE TITLE
OnError is called with no errror

### ISSUE THREAD

**Issue by hoosierfan24** [inaka/EventSource#84]
It is working completely fine with Curl. But in swift it keeps getting an error without any reason why.

CULR `curl --get http://ec2-54-86-125-75.compute-1.amazonaws.com:9000/v1/event-feed/game/f3bcd4e6-0b1f-4169-965e-4276035d64f1`

Displays: 

> event: GameEnded
id: 1509124395663
data: {"id":1509124395663,"gameId":"f3bcd4e6-0b1f-4169-965e-4276035d64f1"}

        
` 

```
let gameUrl = "http://ec2-54-86-125-75.compute-1.amazonaws.com:9000/v1/event-feed/game/f3bcd4e6-0b1f-4169-965e-4276035d64f1"
self.eventSource = EventSource.init(url: gameUrl)
            self.eventSource?.onOpen {
                // When opened
                print("opened")
            }
            self.eventSource?.onError { (error) in
                // When errors
                print(error)
                print(self.eventSource?.description)
                print(self.eventSource?.debugDescription)

            }
            
            self.eventSource?.onMessage { (id, event, data) in
                // Here you get an event without event name!
                print(data)
            }
            
            self.eventSource?.addEventListener("event-name") { (id, event, data) in
                // Here you get an event 'event-name'
                print(data)

            }
`
```

**Comment by andresinaka** [comment]
Hi @hoosierfan24 can you give me more info?? is that consistenly failing?? the onError is being called in two places inside EventSource.swift on this line: 

```open func onError(_ onErrorCallback: @escaping ((NSError?) -> Void))```

and in line 193 inside this method: 

```open func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?)```

Can you put some breakpoints there and see what's going on?

**Comment by vnthanh** [comment]
I'm facing the same issue, our server responsed error with status code 4xx, but i cant managed to catch that error using .onError event (the error is always nil).

**Comment by andresinaka** [comment]
@vnthanh so your server returns a 4xx and the onError method is called but the error parameter in that method is nil?

**Comment by vnthanh** [comment]
Yes. Is that the right behavior?
Thank you for your work.

**Comment by vpdn** [comment]
Since the delegate callback `open func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?)` only reports on client errors, this was the behaviour one would expect from the implementation. Running through the code, it seems a fix has however been provided with this commit https://github.com/inaka/EventSource/commit/84ad8efdcc4434fdef95d2ac33b149151ac32f57. How any status code above 400 should return an error (though the error itself is rather generic).

**Comment by andresinaka** [comment]
`EventSource 3.0` includes:
```
func onComplete(_ onComplete: @escaping ((Int?, Bool?, NSError?) -> Void))
```
And it returns the http status code, a bool that tells if we should re-connect or not based on the [w3](https://www.w3.org/TR/2009/WD-eventsource-20090421/) document and finally the NSError if any.

This should be enough to answer all scenarios.
