### ISSUE TITLE
Pod don't create target

### ISSUE THREAD

**Issue by NikKovIos** [inaka/EventSource#92]
There is a `pod 'IKEventSource'` line in the Podfile  
In console it prints `Using IKEventSource (2.0.0)`  
But in Xcode there are no target for this pod. 
![2018-05-17 10 40 47](https://user-images.githubusercontent.com/16647690/40163192-d927fe94-59be-11e8-8194-936d6c59d159.png)

I did `pod deintegrate` -> `pod update` but still no effect.

**Comment by romainehinds17** [comment]
Same here.

**Comment by drvidal92** [comment]
Have you solved the problem?

**Comment by NikKovIos** [comment]
@drvidal92 Since there is not many files, i did download it and embedded manually in my project.

**Comment by drvidal92** [comment]
@NikKovIos Yes, I have done the same, thanks for the reply

**Comment by jderes** [comment]
Same issue here, can we expect a fix anytime in the near future?

**Comment by AnirudhhRamesh** [comment]
Sorry, which files exactly must be embedded into the framework? I am facing the exact same issue.

**Comment by vpdn** [comment]
I think this is related. See my comment here: https://github.com/inaka/EventSource/issues/95#issuecomment-426067991

**Comment by andresinaka** [comment]
`EventSource 3.0` is working fine with CocoaPods. Install and then `import IKEventSource`
