### ISSUE TITLE
init with Header method not found in Fremework. When i integrated using podfile

### ISSUE THREAD

**Issue by srinathz** [inaka/EventSource#95]
Hi, I integrated the EventSource pod using 

> pod 'EventSource'

 But i did not find init with header method

`public init(url: String, headers: [String : String] = [:]) {}` in the framework. But i could see that method in sample app which you provided. Currently using EventSource (1.0.4).  Am i using correct version ? where else going wrong?

**Comment by vpdn** [comment]
The current podspec on CocoaPods is 2.0.0. It seems 2.1.0 has not been pushed.

You could point the podspec to the repo directly.

```
pod "IKEventSource", :git => "https://github.com/inaka/EventSource"
```

The generated framework is called `IKEventSource` so you'll need to import that (`import IKEventSource`) instead of `EventSource`.

**Comment by andresinaka** [comment]
Version 3.0 is correctly working with CocoaPods. Tested it and seems to be fine.
As @vpdn mentions `import IKEventSource`
