### ISSUE TITLE
By passing header with url data is not giving by event source.

### ISSUE THREAD

**Issue by rahulkumar7** [inaka/EventSource#97]
Please help.

**Comment by elbrujohalcon** [comment]
Hi @rahulkumar7, can you provide an example of the problem you are experiencing, please?

**Comment by rahulkumar7** [comment]
```swift
  let eventSource =   EventSource(url: url, headers: ["Authorization":str])
        eventSource.onOpen {
            print("open")
        }
        eventSource.onMessage { (id, event, data) in
            print(data as Any)
          //  self.updateLabels(id, event: event, data: data)
        }
```
here cam not getting data while printing

**Comment by rahulkumar7** [comment]
Sample given by you also not working while passing with header is any problem with sdk?

**Comment by elbrujohalcon** [comment]
Do you get anything through `eventSource.onError` ?

**Comment by rahulkumar7** [comment]
Error Domain=com.inaka.eventSource.error Code=-1 "(null)" UserInfo={message=HTTP Status Code: 406}

This the error I got.

**Comment by elbrujohalcon** [comment]
Alright, that means your server is responding `406` to your request.
`406` means [Not Acceptable](https://httpstatuses.com/406). Your server is probably incapable of serving event streams 🤷‍♂️.
Have you tried using `curl` or other more basic http request tool to hit the same server?

**Comment by rahulkumar7** [comment]
I got response when I give it in postman.So issue with Api?? I think streaming api will not work in postman.

**Comment by elbrujohalcon** [comment]
Exactly. Postman doesn't request streaming APIs… if it works in postman, that means it will likely fail in EventSource.

**Comment by elbrujohalcon** [comment]
Is it some public server? Can you let me know the url you're trying to hit so I can test it?

**Comment by rahulkumar7** [comment]
Thanks,it worked for me.
